"""Chrome integration commands: native-host, chrome-install, import-chrome."""
from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import sys
from pathlib import Path

from dgp import store
from dgp.cli import _add_common_args, resolve_account, resolve_seed

HOST_NAME = "io.github.hilashemer.dgp"
# ID of linux/chrome-extension, fixed by the "key" in its manifest.json:
# sha256 of the DER public key, first 32 hex digits mapped 0-9a-f -> a-p.
# tests/test_chrome.py checks the two stay in step.
EXTENSION_ID = "iagcagolicncaaanhhmdhfohinomcnhi"

_BROWSER_DIRS = ["google-chrome", "chromium"]


def register(subparsers: argparse._SubParsersAction) -> None:
    p = subparsers.add_parser("native-host", help="Chrome native messaging host (run by Chrome)")
    # Chrome passes the caller origin (and on some platforms more flags); ignore them.
    p.add_argument("chrome_args", nargs="*", help=argparse.SUPPRESS)
    p.set_defaults(func=_cmd_native_host)

    p = subparsers.add_parser("chrome-install",
                              help="Register the native host with Chrome and Chromium")
    p.add_argument("--extension-id", default=EXTENSION_ID, metavar="ID",
                   help=f"Allowed extension ID (default: {EXTENSION_ID})")
    p.add_argument("--dry-run", action="store_true", help="Show what would be written")
    p.set_defaults(func=_cmd_chrome_install)

    p = subparsers.add_parser("import-chrome",
                              help="Import a Google Password Manager CSV export")
    p.add_argument("file", metavar="FILE")
    p.add_argument("--dry-run", action="store_true", help="Report only; change nothing")
    _add_common_args(p)
    p.set_defaults(func=_cmd_import_chrome)


def _cmd_native_host(args: argparse.Namespace) -> int:
    from dgp import nativehost
    # Nothing may reach stderr, not even an interpreter warning.
    devnull = os.open(os.devnull, os.O_WRONLY)
    os.dup2(devnull, 2)
    sys.stderr = open(os.devnull, "w")
    nativehost.serve(sys.stdin.buffer, sys.stdout.buffer)
    return 0


def launcher_path() -> Path:
    return Path.home() / ".local" / "share" / "dgp" / "native-host"


def manifest_paths() -> list[Path]:
    return [Path.home() / ".config" / b / "NativeMessagingHosts" / f"{HOST_NAME}.json"
            for b in _BROWSER_DIRS]


def _cmd_chrome_install(args: argparse.Namespace) -> int:
    ext_id = args.extension_id
    if not re.fullmatch(r"[a-p]{32}", ext_id):
        print(f"Error: '{ext_id}' is not a Chrome extension ID (32 letters a-p).",
              file=sys.stderr)
        return 1
    launcher = launcher_path()
    script = ("#!/bin/sh\n"
              "# Started by Chrome for the DGP extension; written by `dgp chrome-install`.\n"
              f"exec {shlex.quote(sys.executable)} -m dgp native-host\n")
    manifest = json.dumps({
        "name": HOST_NAME,
        "description": "DGP password host",
        "path": str(launcher),
        "type": "stdio",
        "allowed_origins": [f"chrome-extension://{ext_id}/"],
    }, indent=2) + "\n"

    if args.dry_run:
        print(f"would write {launcher}:\n{script}")
        for m in manifest_paths():
            print(f"would write {m}")
        print(manifest, end="")
        return 0

    launcher.parent.mkdir(parents=True, exist_ok=True)
    launcher.write_text(script, encoding="utf-8")
    launcher.chmod(0o755)
    print(f"wrote {launcher}")
    for m in manifest_paths():
        m.parent.mkdir(parents=True, exist_ok=True)
        m.write_text(manifest, encoding="utf-8")
        print(f"wrote {m}")
    return 0


def _cmd_import_chrome(args: argparse.Namespace) -> int:
    from dgp.chromeimport import CsvFormatError, import_rows, read_rows
    try:
        with open(args.file, newline="", encoding="utf-8-sig") as f:
            rows = read_rows(f)
    except (OSError, CsvFormatError, UnicodeDecodeError) as e:
        print(f"Error: cannot read {args.file}: {e}", file=sys.stderr)
        return 1
    seed = resolve_seed(args)
    account = resolve_account(args)
    services = store.read_services()
    rep = import_rows(rows, services, seed, account)

    print(f"{len(rows)} rows: {rep.generated} already generated by DGP, "
          f"{len(rep.new_entries)} new vault entries, "
          f"{rep.already_imported} already imported, {rep.skipped} skipped.")
    for line in rep.sites_added:
        print(f"  site added  {line}")
    for name in rep.new_entries:
        print(f"  new vault   {name}")
    if args.dry_run:
        print("Dry run: nothing written.")
    elif rep.new_entries or rep.sites_added:
        store.write_services(services)
    return 0
