import json
import os
import subprocess
import sys

import pytest

from dgp import engine, store
from dgp.service import DgpService, parse_services
from dgp.vault import decrypt_vault

SEED = "test-seed-not-real"
ACCOUNT = "acct"


@pytest.fixture
def cfg(tmp_path, monkeypatch):
    monkeypatch.setenv("DGP_CONFIG_DIR", str(tmp_path))
    store.write_text_file(store.seed_path(), SEED)
    store.write_text_file(store.account_path(), ACCOUNT)
    store.write_services([
        DgpService(id="gh", name="github", type="alnum"),          # name fallback
        DgpService(id="ex", name="example.org", type="xkcd", sites=["example.org"]),
    ])
    return tmp_path


def _gen(name, t):
    return engine.generate(SEED, name, t, ACCOUNT)


def _write_csv(tmp_path, rows):
    p = tmp_path / "chrome.csv"
    lines = ["name,url,username,password,note"]
    lines += [",".join(r) for r in rows]
    p.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return p


def _run(tmp_path, *args):
    env = {**os.environ, "DGP_CONFIG_DIR": str(tmp_path)}
    return subprocess.run([sys.executable, "-m", "dgp", "import-chrome", *args],
                          env=env, capture_output=True, text=True)


def _by_name():
    return {s.name: s for s in store.read_services()}


def test_import(cfg):
    fake = ["fake-pw-one", "fake-pw-two", "fake-pw-three", "fake-pw-four"]
    csv = _write_csv(cfg, [
        ["GitHub", "https://github.com/session", "me", _gen("github", "alnum")],  # generated
        ["x", "https://www.example.org/login", "u", _gen("example.org", "xkcd")],  # generated, site known
        ["Shop", "https://shop.test/", "alice", fake[0]],                           # new vault
        ["Shop", "https://shop.test/account", "bob", fake[1]],                      # name collision
        ["Empty", "https://empty.test/", "e", ""],                                  # skipped
        ["App", "android://AbC123==@com.foo.bar/", "carol", fake[2]],               # android row
        ["", "https://github.com/", "other", fake[3]],                              # not generated -> vault
    ])
    r = _run(cfg, str(csv))
    assert r.returncode == 0, r.stderr
    for pw in fake + [_gen("github", "alnum"), _gen("example.org", "xkcd"), SEED]:
        assert pw not in r.stdout and pw not in r.stderr
    assert "7 rows: 2 already generated by DGP, 4 new vault entries, 0 already imported, 1 skipped." in r.stdout

    s = _by_name()
    assert s["github"].sites == ["github.com"] and s["github"].type == "alnum"
    assert s["example.org"].sites == ["example.org"]
    assert s["shop.test"].comment == "alice"
    assert s["shop.test"].tags == ["chrome-import"]
    assert s["shop.test"].sites == ["shop.test"]
    assert s["shop.test (bob)"].sites == ["shop.test"]
    assert decrypt_vault(s["shop.test (bob)"].encrypted_secret, SEED, "shop.test (bob)", ACCOUNT) == fake[1]
    assert s["com.foo.bar"].sites == ["com.foo.bar"]
    assert decrypt_vault(s["com.foo.bar"].encrypted_secret, SEED, "com.foo.bar", ACCOUNT) == fake[2]
    assert s["github.com"].type == "vault" and s["github.com"].comment == "other"
    assert "empty.test" not in s
    raw = (cfg / "services.json").read_text()
    assert not any(pw in raw for pw in fake)

    before = raw
    r = _run(cfg, str(csv))
    assert r.returncode == 0
    assert "0 new vault entries, 4 already imported, 1 skipped." in r.stdout
    assert json.loads((cfg / "services.json").read_text()) == json.loads(before)


def test_dry_run_writes_nothing(cfg):
    before = (cfg / "services.json").read_text()
    csv = _write_csv(cfg, [["a", "https://a.test/", "u", "fake-pw"]])
    r = _run(cfg, str(csv), "--dry-run")
    assert r.returncode == 0
    assert "new vault   a.test" in r.stdout and "Dry run" in r.stdout
    assert (cfg / "services.json").read_text() == before


def test_url_column_required(cfg):
    p = cfg / "bad.csv"
    p.write_text("name,password\nx,y\n")
    r = _run(cfg, str(p))
    assert r.returncode == 1 and "url" in r.stderr
