#!/usr/bin/env python3
"""Regenerate web/vectors.json from the Python reference engine.

Two kinds of vector land in the JSON and they are NOT equally authoritative:

  "golden"     - the 74 entries of linux/dgp/testvectors.py, expectations copied
                 straight off the hardcoded literals in that file. Nothing here
                 is computed; these are the numbers the Android app is known to
                 agree with, and they are the real gate.
  "reference"  - inputs this script feeds through linux/dgp/engine.py to fill in
                 what the golden set never covers: aeskey at all, non-ASCII in
                 every field, an empty salt. Weaker evidence - it can only prove
                 the JS agrees with the Python, not that either agrees with the
                 phone - but it is the difference between eight tested types and
                 four.

Seeds here are deliberately, obviously fake. Run from anywhere:
    python3 web/gen-vectors.py
"""
import hashlib
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "linux"))

from dgp.engine import _get_words, generate  # noqa: E402
from dgp.testvectors import VECTORS  # noqa: E402

ALL_TYPES = [
    "hex", "hexlong", "alnum", "alnumlong",
    "base58", "base58long", "xkcd", "xkcdlong", "aeskey",
]

# (seed, account, service) triples chosen for what they exercise, not for realism.
REFERENCE_INPUTS = [
    ("fake-seed-for-tests", "", "example.com"),
    ("fake-seed-for-tests", "alice", "example.com"),
    ("fake-seed-for-tests", "", ""),               # empty salt
    ("", "", "example.com"),                        # empty password material
    ("", "", ""),                                   # both empty
    ("fünf-テスト-\U0001f511", "é", "café.example"),  # UTF-8: 2/3/4-byte
    ("fake-seed-for-tests", "b", "ab"),             # seed+account vs seed+account boundary, pair 1
    ("fake-seed-for-testsb", "", "ab"),             # ...pair 2: must derive identically
]


# The seed check-word. There is no Python counterpart to lean on: the only
# implementation is DgpEngine.fingerprintWord / deriveFingerprintBytes in
# app/src/main/java/com/dgp/engine/DgpEngine.kt, so this recomputes it from that
# source directly. Two BIP-39 words, low-order first (divmod by 2048), lowercase,
# joined by "-", over 32 bytes salted with a reserved domain string. Nonce and
# flag gallery deliberately not reproduced - the web UI shows only the word.
FINGERPRINT_SALT = b"dgp-flag-fp:v1"


def fingerprint_word(seed: str, account: str) -> str:
    fp = hashlib.pbkdf2_hmac("sha1", (seed + account).encode("utf-8"),
                             FINGERPRINT_SALT, 42000, 32)
    n = int.from_bytes(fp, "big")
    words = []
    for _ in range(2):
        n, mod = divmod(n, 2048)
        words.append(_get_words()[mod])
    return "-".join(words)


def main() -> int:
    golden = [
        {"seed": v.seed, "account": v.account, "service": v.name,
         "type": v.type, "expected": v.expected}
        for v in VECTORS
    ]
    reference = [
        {"seed": s, "account": a, "service": n, "type": t,
         "expected": generate(s, n, t, a)}
        for (s, a, n) in REFERENCE_INPUTS
        for t in ALL_TYPES
    ]
    # An unknown type is a specified return value, not an error path.
    reference.append({
        "seed": "fake-seed-for-tests", "account": "", "service": "example.com",
        "type": "no-such-type", "expected": "unknown type",
    })

    checkword = [
        {"seed": s, "account": a, "expected": fingerprint_word(s, a)}
        for (s, a, _) in REFERENCE_INPUTS
    ]

    out = {
        "_comment": "Generated by web/gen-vectors.py - do not hand-edit. "
                    "golden = verbatim from linux/dgp/testvectors.py; "
                    "reference = computed from linux/dgp/engine.py; "
                    "checkword = recomputed from DgpEngine.kt (no Python port exists).",
        "golden": golden,
        "reference": reference,
        "checkword": checkword,
    }
    path = ROOT / "web" / "vectors.json"
    path.write_text(json.dumps(out, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {path}: {len(golden)} golden, {len(reference)} reference, "
          f"{len(checkword)} check-word")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
